### ISSUE TITLE
Error in reading simple.in

### ISSUE THREAD

**Issue by benjaminfaber** [itpplasma/SIMPLE#10]
Using the example `simple.in` file from `examples/simple.in` and modifying the wout file for the desired equilibrium, I encounter the following error:

```
At line 145 of file /home/bfaber/projects/SIMPLE/SRC/main.f90 (unit = 1, file = 'simple.in')
Fortran runtime error: Bad real number in item 1 of list input
```

When I comment out that line in `main.f90` and hard code `cut_in_per` to 0, then `simple.x` runs and completes.

**Comment by krystophny** [comment]
Fixed in 1ff28fb
