### ISSUE TITLE
isw_field_type = 1 error?

### ISSUE THREAD

**Issue by benjaminfaber** [itpplasma/SIMPLE#36]
Hi,

@JakeNeau and I are trying to run SIMPLE with initial particle positions specified by VMEC coordinates.  We set `isw_field_type = 1` in `simple.in`.  However, we run `simple.x` with this input, we get an error stating "Illegal field type" for `eval_field` and the message of `Unknown field type`.  Is this the correct way to be runing SIMPLE with particle positions in VMEC coordinates and a corresponding VMEC file?  Furthermore, what is `isw_field_type` specifying?

Thanks,
Ben

**Comment by krystophny** [comment]
Hi Ben, that's fine - you can use either canonical or Boozer coordinates as a switch. Those are only used internally and initial positions are always VMEC coordinates.

**Comment by benjaminfaber** [comment]
Thank, Christopher, I appreciate the clarification!
